version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./:/usr/src/app
    ports:
      - 8092:80

  binary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80