version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-env
    volumes:
      - ./:/usr/src/app
    environment:
      - Port=80
    ports:
      - 8092:80

  binary:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - Port=80
    ports:
      - 8080:80